"""Shared bounds for work that can outlive an ordinary HTTP job."""

MAX_LONG_JOB_SECONDS = 570
DEFAULT_LONG_JOB_SECONDS = MAX_LONG_JOB_SECONDS
MAINTENANCE_PUBLICATION_RESERVE_SECONDS = 60
MAINTENANCE_LEASE_GRACE_SECONDS = 15
